---
- name: Network | create LB network
  openstack.cloud.network:
    cloud: pbos-octavia
    name: "{{ octavia_mgmt_network_name }}"
    state: present
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true

- name: Network | get LB network info
  openstack.cloud.networks_info:
    cloud: pbos-octavia
    name: "{{ octavia_mgmt_network_name }}"
  register: result
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true

- name: Network | set fact for LB network id
  ansible.builtin.set_fact:
    lb_network_id: "{{ result.openstack_networks[0].id }}"

- name: Network | create LB subnet
  openstack.cloud.subnet:
    cloud: pbos-octavia
    network_name: "{{ octavia_mgmt_network_name }}"
    name: "{{ octavia_mgmt_subnet_name }}"
    cidr: "{{ octavia_mgmt_subnet_cidr }}"
    no_gateway_ip: true
    dns_nameservers:
      - 8.8.8.8
    allocation_pool_start: "{{ octavia_mgmt_subnet_start }}"
    allocation_pool_end: "{{ octavia_mgmt_subnet_end }}"
    state: present
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true

- name: Network | get LB subnet info
  openstack.cloud.subnets_info:
    cloud: pbos-octavia
    name: "{{ octavia_mgmt_subnet_name }}"
  register: result
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true

- name: Network | set fact for LB subnet id
  ansible.builtin.set_fact:
    lb_subnet_id: "{{ result.openstack_subnets[0].id }}"

- name: Network | Set up health managers
  ansible.builtin.include_tasks: hm_setup.yml
  loop: "{{ groups['octavia'] }}"
  loop_control:
    extended: true
...
